# Generated by Django 3.2.16 on 2022-10-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['id'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
